name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-Python:
    runs-on: macos-12
    steps:
      - run: brew install python@3.11
  Test-Formula:
    runs-on: macos-12
    steps:
      - run: brew uninstall azure-cli
      - run: wget https://hangstorage.blob.core.windows.net/public/azure-cli.rb && brew install --build-from-source ./azure-cli.rb
  Test-Build:
    runs-on: macos-12
    steps:
      - run: brew uninstall azure-cli
      - run: brew install --build-from-source azure-cli
