name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sed 's/gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg/gpg --dearmor > /etc/apt/keyrings/microsoft.gpg' | sudo bash
      - run: az -v
