name: GitHub Actions Demo
run-name: Test homebrew
on: [push]
jobs:
  Test-Python-macos12:
    runs-on: macos-12
    steps:
      - run: which python3.11
      - run: python3.11 --version
      - run: ls -la /usr/local/bin/python3.11
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
      - run: brew update
      - run: brew uninstall azure-cli
      - run: brew install --overwrite python@3.11
        if: always()
  Test-Python-macos13:
    runs-on: macos-13
    steps:
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
      - run: brew update
      - run: brew uninstall azure-cli
      - run: brew install python@3.11
        if: always()
  Test-Python-macos14:
    runs-on: macos-14
    steps:
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
      - run: brew update
      - run: brew uninstall azure-cli
      - run: brew install python@3.11
        if: always()
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
