name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: id
      - run: env
      - run: az -v
      - run: sudo apt remove azure-cli
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sed 's/--dearmor -o/--dearmor >/' | sudo bash
      - run: az -v
