name: GitHub Actions Demo
run-name: Test homebrew
on: [push]
jobs:
  Test-Python-macos12:
    runs-on: macos-12
    steps:
      - run: which python3.11
      - run: echo $PATH
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: ls -la /Users/runner/hostedtoolcache/Python/3.11.9/x64/bin/python3.11
      - run: ls -la /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
      - run: python3.11 --version
      - run: brew update
      - run: brew uninstall azure-cli
      - run: brew install --overwrite python@3.11
        if: always()
      - run: python3.11 --version
      - run: ls -la /usr/local/bin/2to3-3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: which python3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: python3.11 --version
      - run: echo $PATH
  Test-Python-macos13:
    runs-on: macos-13
    steps:
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
      - run: brew update
      - run: brew uninstall azure-cli
      - run: brew install python@3.11
        if: always()
  Test-Python-macos14:
    runs-on: macos-14
    steps:
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
      - run: brew update
      - run: brew uninstall azure-cli
      - run: brew install python@3.11
        if: always()
      - run: file /usr/local/bin/2to3-3.11
      - run: ls -la /usr/local/bin/2to3-3.11
      - run: readlink /usr/local/bin/2to3-3.11 
