name: GitHub Actions Demo
run-name: Test homebrew
on: [push]
jobs:
  Test-Python:
    runs-on: macos-12
    steps:
      - run: brew install python@3.11
  Test-Formula:
    runs-on: macos-12
    environment: Test
    steps:
      - run: brew uninstall azure-cli
      - run: wget $FORMULA && brew install --build-from-source ./azure-cli.rb
  Test-Build:
    runs-on: macos-12
    steps:
      - run: brew uninstall azure-cli
      - run: brew install --build-from-source azure-cli
