name: GitHub Actions Demo
run-name: Test pip
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: pip list
    - run: pip install markupsafe==2.0.1 -vvv
